force-app/main/default/objects/PSChatBotPackParam__mdt/PSChatBotPackParam__mdt.object-meta.xml
<CustomObject>
    <label>PSChatBotPackParam</label>
    <pluralLabel>PSChatBotPackParams</pluralLabel>
</CustomObject>

force-app/main/default/objects/PSChatBotPackParam__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PSChatBotPack_GetParams.cls
global with sharing class PSChatBotPack_GetParams {
    global static void test()
    {
        String val = getParam('GoogleMapsAPIKey');
        System.debug('value=' + val);
        val = getParam('BadLabel');
        System.debug('value=' + val);

    }

    //@InvocableMethod(label='Get Config Param (PSChatBotPack)')
    global static String getParam(String label)
    {
        String retVal = null;
        try {
            PSChatBotPackParam__mdt param = PSChatBotPackParam__mdt.getInstance(label);
            retVal = param.value__c;
        } catch (Exception e) {
            // do nothing
        }

        return retVal;

    }

    global class getParamRequest {
        @InvocableVariable(required=true)
        global String label;
      }
}